version: '3.4'
services:
  # bot service
  bot:
    image: beproductive
    restart: on-failure
    # compile the source + run
    build: .
    # the config file
    env_file:
      - ./config.env
    environment:
      # this is needed so the wait script knows what to wait for
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 60
      WAIT_BEFORE_HOSTS: 20
      WAIT_SLEEP_INTERVAL: 3
    # waits for MariaDB
    depends_on:
      - db
  # database service
  db:
    restart: always
    image: mariadb
    # persistent database storage
    volumes:
      - db:/data
    # database + account credentials
    environment:
      - MYSQL_DATABASE=bp
      - MYSQL_USER=help
      - MYSQL_PASSWORD=me
      - MYSQL_ROOT_PASSWORD=giggity
volumes:
  # database volume
  db: